#!/usr/bin/env bash
# inject_modules.sh
# Copy converted Rust modules into the kernel source tree and wire them into Kbuild.
set -euo pipefail

KERNEL_SRC=""
RUST_SRC=""
ARCH="x86_64"

while [[ $# -gt 0 ]]; do
    case $1 in
        --kernel-src) KERNEL_SRC="$2"; shift 2 ;;
        --rust-src)   RUST_SRC="$2";   shift 2 ;;
        --arch)       ARCH="$2";       shift 2 ;;
        *) echo "Unknown: $1" >&2; exit 1 ;;
    esac
done

[ -n "$KERNEL_SRC" ] || { echo "ERROR: --kernel-src required" >&2; exit 1; }
[ -n "$RUST_SRC"   ] || { echo "ERROR: --rust-src required" >&2; exit 1; }

DEST="$KERNEL_SRC/rust/converted"
mkdir -p "$DEST"

echo "[inject_modules] Copying Rust modules to $DEST"

# Copy generated Rust source files
for f in "$RUST_SRC"/generated/**/*.rs "$RUST_SRC"/generated/*.rs; do
    [ -f "$f" ] || continue
    STEM=$(basename "$f" .rs)
    cp "$f" "$DEST/${STEM}.rs"
    echo "  → $DEST/${STEM}.rs"
done

# Copy bindings
if [ -f "$RUST_SRC/bindings/auto_generated.rs" ]; then
    cp "$RUST_SRC/bindings/auto_generated.rs" \
       "$KERNEL_SRC/rust/bindings/converted_bindings.rs"
fi

# Generate Kbuild entry for converted modules
KBUILD="$DEST/Kbuild"
cat > "$KBUILD" <<KBUILD_EOF
# Kbuild - Auto-generated by inject_modules.sh
# Converted Rust modules (formerly C)

obj-\$(CONFIG_RUST_CONVERTED_MODULES) += converted_modules.o
KBUILD_EOF

# Generate a lib.rs that includes each converted module
LIB="$DEST/lib.rs"
cat > "$LIB" <<'LIB_EOF'
// SPDX-License-Identifier: GPL-2.0
//! Auto-converted Rust modules (formerly C sources).
//! Generated by the linux-c2rust-pipeline.

#![no_std]
#![feature(allocator_api)]

extern crate kernel;

LIB_EOF

for f in "$DEST"/*.rs; do
    [ -f "$f" ] || continue
    STEM=$(basename "$f" .rs)
    [ "$STEM" = "lib" ] && continue
    echo "pub mod $STEM;" >> "$LIB"
done

# Add our directory to the kernel's rust/Makefile if not already present
RUST_MK="$KERNEL_SRC/rust/Makefile"
ENTRY="obj-\$(CONFIG_RUST_CONVERTED_MODULES) += converted/"
if ! grep -qF "$ENTRY" "$RUST_MK" 2>/dev/null; then
    echo "" >> "$RUST_MK"
    echo "# Converted modules from C (auto-generated)" >> "$RUST_MK"
    echo "$ENTRY" >> "$RUST_MK"
    echo "[inject_modules] Added entry to $RUST_MK"
fi

# Add Kconfig entry if not present
RUST_KC="$KERNEL_SRC/rust/Kconfig"
if ! grep -q 'RUST_CONVERTED_MODULES' "$RUST_KC" 2>/dev/null; then
    cat >> "$RUST_KC" <<'KCONFIG_EOF'

config RUST_CONVERTED_MODULES
    bool "Auto-converted Rust modules (C2Rust)"
    depends on RUST
    default n
    help
      Enable Rust modules that were automatically converted from C sources
      using the c2rust pipeline. These modules undergo security auditing
      and compatibility verification before inclusion.
      If unsure, say N.
KCONFIG_EOF
    echo "[inject_modules] Added Kconfig entry"
fi

echo "[inject_modules] Done. $(ls "$DEST"/*.rs | wc -l) modules injected."
